debian/postinst, restart logstart if already configured

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,11 +1,49 @@
 #!/bin/sh
+# postinst script for #PACKAGE#
+#
+# see: dh_installdeb(1)
 
-chown -R logstash:logstash /usr/share/logstash
-chown -R logstash /var/log/logstash
-chown logstash:logstash /var/lib/logstash
-sed -i \
-  -e 's|# path.config:|path.config: /etc/logstash/conf.d|' \
-  -e 's|# path.logs:|path.logs: /var/log/logstash|' \
-  -e 's|# path.data:|path.data: /var/lib/logstash|' \
-  /etc/logstash/logstash.yml
-/usr/share/logstash/bin/system-install /etc/logstash/startup.options
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+    configure)
+      chown -R logstash:logstash /usr/share/logstash
+      chown -R logstash /var/log/logstash
+      chown logstash:logstash /var/lib/logstash
+      sed -i \
+         -e 's|# path.config:|path.config: /etc/logstash/conf.d|' \
+         -e 's|# path.logs:|path.logs: /var/log/logstash|' \
+         -e 's|# path.data:|path.data: /var/lib/logstash|' \
+        /etc/logstash/logstash.yml
+      /usr/share/logstash/bin/system-install /etc/logstash/startup.options
+      [ -e /etc/logstash/logstash.yml] && systemctl restart logstash
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
